version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - .:/srv/app
    links:
      - db
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: playground
    ports:
      - 3306:3306
