version: "3.7"

services:
  app:
    build:
      context: .
    volumes:
      - .:/srv/app
    links:
      - db
  db:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123root123
      MYSQL_DATABASE: playground
    ports:
      - 3306:3306
